export const ActivityActions = {
  MILESTONE_CREATED: "MILESTONE_CREATED",
  MILESTONE_UPDATED: "MILESTONE_UPDATED",
  MILESTONE_COMPLETED: "MILESTONE_COMPLETED",
  STATUS_UPDATED: "STATUS_UPDATED",
  PHOTO_UPLOADED: "PHOTO_UPLOADED",
  VIDEO_UPLOADED: "VIDEO_UPLOADED",
  CHECKLIST_UPDATED: "CHECKLIST_UPDATED",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  APPROVAL_GRANTED: "APPROVAL_GRANTED",
  APPROVAL_REJECTED: "APPROVAL_REJECTED"
} as const